### ISSUE TITLE
Asset tokens docs

### ISSUE THREAD

**Issue by rbosker** [six7/figma-tokens-docs#39]
**Related issue:** https://github.com/six7/figma-tokens/issues/1265

**Name doc:** Asset tokens

**Video walk through:** 
**Doc:**

**Comment by six7** [comment]
I'll create a video explaining
- how to create them
- how to apply them
- how to effectively use them for e.g. swapping Logos
- Mention the caveat about the CORS issue

The docs itself should probably contain some information on the token type (what value "value" needs to be, type) as well as information about the CORS header that people will need to set. Or use a CORS Proxy.
