### ISSUE TITLE
Onboarding docs

### ISSUE THREAD

**Issue by rbosker** [six7/figma-tokens-docs#47]
**Related issue:** https://github.com/six7/figma-tokens/issues/1200
https://github.com/six7/figma-tokens/issues/1261
https://github.com/six7/figma-tokens/issues/1262
https://github.com/six7/figma-tokens/issues/1263

**Name doc:** Onboarding

**Video walk through:** not needed
**Doc:**

**Comment by six7** [comment]
We won't need docs for Onboarding. Onboarding can be seen as a way to help users discover the Docs and the basics of the plugin, but we won't need to explain how that works. Closing this one.
